### ISSUE TITLE
springboot-actuator的management.port没起作用？

### ISSUE THREAD

**Issue by LeiYangGH** [xuwujing/springBoot-study#28]
在springboot-actuator项目的src/main/resources/application.yml里面
```yaml
server:
  port: 8181 
management:
  security:
    enabled: false #关掉安全认证
  port: 8888 #管理端口
  context-path: /monitor #actuator的访问路径
```
启动后，访问管理端口只能用诸如http://localhost:8181/actuator
但没看到任何endpoint可以用8888端口或者/monitor访问的，都是连接被拒绝。
请举例说明这两个配置的作用？谢谢。
